// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://teeiqfgegkshfizvzmqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlZWlxZmdlZ2tzaGZpenZ6bXFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjY0ODcsImV4cCI6MjA2OTU0MjQ4N30.h_FqWHJ9ArF5Ej0tdiS6qrynnWwxp_NApZ7Xbi-AQhg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});